apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: john.doe
  profile:
    displayName: John Doe
    email: iambatman@thoughtworks.com
    picture:
spec:
  memberOf: [thoughtworks, awesome-project]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: al06
  profile:
    displayName: Ankit Luthra
    email: ankitluthra06@gmail.com
    picture:
spec:
  memberOf: [platform-engg-team, thoughtworks]